Workout.Web/Controllers/WorkoutController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Workout.Business.Models.RequestModels;
using Workout.Business.Processes;
using Workout.Data.Processes;

namespace Workout.Web.Controllers
{
    public class WorkoutController : Controller
    {
        #region Decleration
        private WorkoutProcesses workoutProcesses = new WorkoutProcesses();
        private string jsonString = String.Empty;

        #endregion

        #region Error Handling
        protected override void OnException(ExceptionContext filterContext)
        {
            Exception ex = filterContext.Exception;
            LogProcesses.ErrorLog(ex);
        }
        #endregion

        #region Workout Processes
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileExtension = Path.GetExtension(file.FileName);
                if (fileExtension == ".mp4")
                {
                    var fileID = Guid.NewGuid();
                    var path = Path.Combine(Server.MapPath("~/Assets/Videos"), fileID.ToString() + fileExtension);
                    file.SaveAs(path);
                    Session.Add("FileName", fileID.ToString() + fileExtension);
                }
                else
                {
                    return RedirectToAction("AddWorkout", "Home", new { error = "You can upload only mp4 files" });
                }
            }
            return RedirectToAction("AddWorkout", "Home");
        }
        [HttpPost]
        public ActionResult UploadFileForEdit(HttpPostedFileBase file, string workoutID)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileExtension = Path.GetExtension(file.FileName);
                if (fileExtension == ".mp4")
                {
                    var fileID = Guid.NewGuid();
                    var path = Path.Combine(Server.MapPath("~/Assets/Videos"), fileID.ToString() + fileExtension);
                    file.SaveAs(path);
                    Session.Add("FileName", fileID.ToString() + fileExtension);
                }
                else
                {
                   return RedirectToAction("EditWorkout", "Home", new { workoutID = workoutID, error = "You can upload only mp4 files" });
                }
            }
            return RedirectToAction("EditWorkout", "Home", new { workoutID = workoutID });
        }

        [HttpPost]
        public ActionResult UploadCertificate(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileExtension = Path.GetExtension(file.FileName);
                if (fileExtension == ".pdf" || fileExtension == ".doc" || fileExtension == ".docx")
                {
                    var fileID = Guid.NewGuid();
                    var path = Path.Combine(Server.MapPath("~/Assets/Certificates"), fileID.ToString() + fileExtension);
                    file.SaveAs(path);
                    Session.Add("FileNameOfCertificate", fileID.ToString() + fileExtension);
                }
                else
                {
                    return RedirectToAction("MyCertificates", "Home", new { error = "You can upload only pdf/doc/docx files" });
                }
            }
            return RedirectToAction("MyCertificates", "Home");
        }

        //[HttpPost]
        //public ActionResult UploadCertificateForEdit(HttpPostedFileBase file, string certificateId)
        //{
        //    if (file != null && file.ContentLength > 0)
        //    {
        //        var fileExtension = Path.GetExtension(file.FileName);
        //        var fileID = Guid.NewGuid();
        //        var path = Path.Combine(Server.MapPath("~/Assets/Certificates"), fileID.ToString() + fileExtension);
        //        file.SaveAs(path);
        //        Session.Add("FileNameOfCertificate", fileID.ToString() + fileExtension);
        //    }
        //    return RedirectToAction("TrainerCertificates", "Admin");
        //}

        [HttpPost]
        public JsonResult CreateWorkout()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<WorkoutRequest>(ReadJson());
                return Json(workoutProcesses.CreateWorkout(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public JsonResult UpdateWorkout()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<UpdateWorkoutRequest>(ReadJson());
                return Json(workoutProcesses.UpdateWorkout(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public JsonResult CreateProgram()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<CreateProgramRequest>(ReadJson());
                return Json(workoutProcesses.CreateProgram(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public JsonResult UpdateProgram()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<UpdateProgramRequest>(ReadJson());
                return Json(workoutProcesses.UpdateProgram(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult GetWorkout()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<GetWorkoutRequest>(ReadJson());
                return Json(workoutProcesses.GetWorkout(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult AddWorkoutToProgram()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<AddToProgramRequest>(ReadJson());
                return Json(workoutProcesses.AddWorkoutToProgram(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult GetProgram()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<GetProgramRequest>(ReadJson());
                return Json(workoutProcesses.GetProgram(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult GetAllWorkouts()
        {
            try
            {
                return Json(workoutProcesses.GetAllWorkout(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpGet]
        public JsonResult GetAllPrograms()
        {
            try
            {
                return Json(workoutProcesses.GetAllPrograms(false, false), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult JoinToProgram()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<JoinToProgramRequest>(ReadJson());
                return Json(workoutProcesses.JoinToProgram(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        //public JsonResult JoinToProgram(Guid ProgramID)
        //{
        //    try
        //    {

        //        return Json(workoutProcesses.JoinToProgram(ProgramID), JsonRequestBehavior.AllowGet);
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //}
        public ActionResult JoinToProgram(Guid ProgramID)
        {
            try
            {
               var result = workoutProcesses.JoinToProgram(ProgramID);
                return RedirectToAction("AllPrograms", "Home", new {message = "Register Success"});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Comment Processes
        [HttpPost]
        public JsonResult AddComment()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<AddCommentRequest>(ReadJson());
                return Json(workoutProcesses.AddComment(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public JsonResult GetComments()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<GetCommentRequest>(ReadJson());
                return Json(workoutProcesses.GetComments(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region Rate Processes
        [HttpPost]
        public JsonResult AddRate()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<AddRateRequest>(ReadJson());
                return Json(workoutProcesses.AddRate(request), JsonRequestBehavior.AllowGet);
            }

Workout.Web/Views/Home/AddProgram.cshtml
@using Workout.Business.Models.Enums

@{
    ViewBag.Title = "AddProgram";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}

@{
    if (Model.Workout.Count > 0)
    {

        <h1>Add Program</h1><br />
        <style>
          

            h1 {
                padding: .2em;
                margin: 0;
            }

            #products {
                float: left;
                width: 500px;
                margin-right: 2em;
            }

            #cart {
                width: 200px;
                float: left;
                margin-top: 1em;
            }
                /* style the list to maximize the droppable hitarea */
                #cart ol {
                    margin: 0;
                    padding: 1em 0 1em 3em;
                }
        </style>
        <script>

            $(function () {
                var $tabs1 = $('#table-draggable1');
                $("tbody.connectedSortable")
                    .sortable({
                        connectWith: ".connectedSortable",
                        items: "> tr:not(:first-child)",
                        appendTo: $tabs1,
                        helper: "clone",
                        zIndex: 999990,
                        remove: function (event, ui) {
                            ui.item.clone().appendTo('#table-draggable2');
                            $(this).sortable('cancel');
                        }
                    })
                    .disableSelection()
                ;

                var $tabs = $('#table-draggable2');
                $("tbody.connectedSortable")
                    .sortable({
                        connectWith: ".connectedSortable",
                        items: "> tr:not(:first-child)",
                        appendTo: $tabs,
                        helper: "clone",
                        zIndex: 999990
                    })
                    .disableSelection()
                ;

                var $tab_items = $(".nav-tabs > li", $tabs).droppable({
                    accept: ".connectedSortable tr",
                    hoverClass: "ui-state-hover",

                    drop: function (event, ui) {
                        
                        return false;
                    }
                });
            });

        </script>
        <form class="form-horizontal create-program-form">
            <fieldset>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="form-program-title">Title</label>
                    <div class="col-md-4">
                        <input id="title" name="title" type="text" placeholder="Sprint Title" class="form-control input-md" required="">

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="form-program-subtitle">Subtitle</label>
                    <div class="col-md-4">
                        <input id="subtitle" name="subtitle" type="text" placeholder="Sprint Subtitle" class="form-control input-md" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="form-program-level">Level</label>
                    <div class="col-md-4">
                        <select id="form-program-level" name="level" class="form-select form-gender" autocomplete="off" required="">
                            @{
                                Array levels = Enum.GetValues(typeof(Workout.Business.Models.Enums.ProgramLevels));

                                foreach (var i in levels)
                                {
                                    <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof(Workout.Business.Models.Enums.ProgramLevels), i)</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="form-program-category">Category</label>
                    <div class="col-md-4">
                        <select id="form-program-category" name="level" class="form-select form-gender" autocomplete="off" required="">
                            @{
                                Array category = Enum.GetValues(typeof(Workout.Business.Models.Enums.ProgramCategory));

                                foreach (var i in category)
                                {
                                    <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof(Workout.Business.Models.Enums.ProgramCategory), i)</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="form-program-information">Information</label>
                    <div class="col-md-4">
                        <textarea class="form-control" id="information" name="information" placeholder="Program Explanation Here ..."></textarea>
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-md-4 control-label" for="form-program-selectedworkouts">Your Workouts</label>
                    <div id="AllWorkouts" class="col-md-4">

                        <h4>All Workouts of You</h4>

                        <div class="form-group">
                            <label class="col-md-4 control-label" for="form-workout-category">Category</label>
                            <div class="col-md-4">
                                <select id="form-workout-category" name="category" class="form-select form-gender" autocomplete="off" required="">
                                    @{
                                        Array categories = Enum.GetValues(typeof (Workout.Business.Models.Enums.WorkoutCategory));

                                        foreach (var i in categories)
                                        {
                                            <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof (Workout.Business.Models.Enums.WorkoutCategory), i)</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="form-workout-class">Class</label>
                            <div class="col-md-4">
                                <select id="form-workout-class" name="wclass" class="form-select form-class" autocomplete="off" required="">
                                    @{
                                        Array classes = Enum.GetValues(typeof (Workout.Business.Models.Enums.WorkoutClass));

                                        foreach (var i in classes)
                                        {
                                            <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof (Workout.Business.Models.Enums.WorkoutClass), i)</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <a href="#" class="btn btn-primary" onclick="GetFilteredWorkouts()"> Get Workouts </a>
                        </div>

                        <table class="table table-bordered table-striped table-hover table-condensed table-responsive" id='table-draggable1'>
                          
                            <tbody class="connectedSortable">
                                <tr class="my-workouts-tr">
                                    <th>
                                        Workout
                                    </th>
                                    <th>
                                        Category
                                    </th>
                                    <th>
                                        Class
                                    </th>
                                    <th>
                                        Period
                                    </th>
                                    <th>
                                        Repeat
                                    </th>
                                </tr>
                            
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="form-group ">
                    <label class="col-md-4 control-label" for="form-program-selectedworkouts">Selected Workouts</label>
                    <div id="SelectedWorkouts" class="col-md-4">

                        <h4>Selected Workouts</h4>
                    
                        <table class="table table-bordered table-striped table-hover table-condensed table-responsive" id='table-draggable2'>
                         
                            <tbody class="connectedSortable">
                                <tr>
                                    <th>
                                        Workout
                                    </th>
                                    <th>
                                        Category
                                    </th>
                                    <th>
                                        Class
                                    </th>
                                    <th>
                                        Period
                                    </th>
                                    <th>
                                        Repeat
                                    </th>
                                </tr>
                           
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="form-group">
                    <a href="#" class="btn btn-danger btn-create-program"><i class="fa fa-sign-out fa-fw"></i>Save</a>
                </div>

            </fieldset>
        </form>


    }
    else
    {
        <h2>Add workout before create program</h2>
    }

}

Workout.Web/Views/Home/EditWorkout.cshtml
@{
    ViewBag.Title = "EditWorkout";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
    var workout = ViewBag.Workout.Workout;
    var videoID = Session["FileName"];

    if (videoID == null)
    {
        videoID = @workout.Video;
    }


}

<h2>EditWorkout</h2>
<br />
<h4>Step 1 : Upload a video if you want to change</h4>
<div class="form-group">
    @using (Html.BeginForm("UploadFileForEdit", "Workout", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <input type="file" name="file" style="display: inline-block !important;"/>
        <input type="submit" value="Upload"/>
        <input type="hidden" name="workoutID" value="@workout.ID"/>
    }
</div>
<script>
    var parseQueryString = function () {

        var str = window.location.search;
        var objURL = {};

        str.replace(
            new RegExp("([^?=&]+)(=([^&]*))?", "g"),
            function ($0, $1, $2, $3) {
                objURL[$1] = $3;
            }
        );
        return objURL;
    };
    var params = parseQueryString();

    var error = params["error"];

    if (typeof error !== "undefined") {
        var text = decodeURIComponent(error);
        alert(text);
    }
</script>
<h4>Step 2 : Change the form and save</h4>
<form class="form-horizontal update-workout-form">
    <fieldset>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-name">Workout Name</label>
            <div class="col-md-4">
                <input id="form-workout-name" name="name" type="text" value="@workout.Name" class="form-control input-md" required="">

            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-title">Title</label>
            <div class="col-md-4">
                <input id="form-workout-title" name="title" type="text" value="@workout.Title" class="form-control input-md" required="">

            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-subtitle">Subtitle</label>
            <div class="col-md-4">
                <input id="form-workout-subtitle" name="subtitle" type="text" value="@workout.Subtitle" class="form-control input-md" required="">

            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-information">Information</label>
            <div class="col-md-4">
                <textarea class="form-control" id="form-workout-information" name="information">@workout.Information</textarea>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-category">Category</label>
            <div class="col-md-4">
                <select id="form-workout-category" name="category" class="form-select form-gender" autocomplete="off" required="">
                    @{
                        Array categories = Enum.GetValues(typeof(Workout.Business.Models.Enums.WorkoutCategory));

                        foreach (var i in categories)
                        {
                            if (workout.Category == Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutCategory), i))
                            {
                                <option value="@Convert.ToInt32(i)" selected>@Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutCategory), i)</option>
                            }
                            else
                            {
                                <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutCategory), i)</option>
                            }
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-class">Class</label>
            <div class="col-md-4">
                <select id="form-workout-class" name="wclass" class="form-select form-class" autocomplete="off" required="">
                    @{
                        Array classes = Enum.GetValues(typeof(Workout.Business.Models.Enums.WorkoutClass));

                        foreach (var i in classes)
                        {
                            if (workout.Class == Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutClass), i))
                            {
                                <option value="@Convert.ToInt32(i)" selected>@Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutClass), i)</option>
                            }
                            else
                            {
                                <option value="@Convert.ToInt32(i)">@Enum.GetName(typeof(Workout.Business.Models.Enums.WorkoutClass), i)</option>
                            }
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="form-workout-video">Video ID</label>
            <div class="col-md-4">
                <input id="form-workout-video" name="video" type="text" placeholder="Please upload your video file" class="form-control input-md" value="@videoID" required="" readonly="readonly">
            </div>
        </div>
        <input type="hidden" id="workout-id" value="@workout.ID" />
        <div class="form-group">
            <a href="#" class="btn btn-danger btn-update-workout"><i class="fa fa-sign-out fa-fw"></i>Update</a>
        </div>

    </fieldset>
</form>

Workout.Web/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Workout - Login</title>

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Assets/assets/font-awesome/css/font-awesome.min.css">
    <link href="~/Assets/style.css" rel="stylesheet" />
    <link href="~/Assets/form-elements.css" rel="stylesheet" />

    <link rel="shortcut icon" href="assets/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Assets/ico/apple-touch-icon-57-precomposed.png">

</head>
<body>
    <div class="top-content">

        <div class="inner-bg">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2 text">
                        <h1><strong>Workout</strong> - Login</h1>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 form-box">
                        <div class="form-top">
                            <div class="form-top-left">
                                <h3>Login to Workout</h3>
                                <p>Enter your email and password to log on:</p>
                            </div>
                            <div class="form-top-right">
                                <i class="fa fa-key"></i>
                            </div>
                        </div>
                        <div class="form-bottom">
                            <form role="form"  class="login-form">
                                <div class="form-group">
                                    <label class="sr-only" for="form-email">Email</label>
                                    <input type="text" name="email" placeholder="Email..." class="form-email form-control" id="form-email">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="form-password">Password</label>
                                    <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                                    <input type="hidden" value="@Request.QueryString["url"]" name="url" />
                                </div>
                                <a href="#" class="btn-login btn btn-success" style="margin-left: 10px;">Sign In</a>
                                <a href="/Home/Register" class="btn btn-primary" style="margin-left: 10px;">Register</a>
                                <a href="/Home/SecurityControl" class="btn btn-danger" style="margin-left: 10px;">Reset Password</a>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <script src="~/Assets/js/jquery-1.11.1.min.js"></script>
    <script src="~/Assets/js/jquery.backstretch.min.js"></script>
    <script src="~/Assets/js/scripts.js"></script>
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/Sha1.js"></script>
    <script src="~/Assets/js/Functions.js"></script>
    <script src="~/Assets/js/jquery.validate.min.js"></script>
    <!--[if lt IE 10]>
        <script src="~/Assets/js/placeholder.js"></script>
    <![endif]-->

</body>

</html>

Workout.Web/Views/Home/TrainerPanel.cshtml
@{
    ViewBag.Title = "TrainerPanel";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}

Workout.Web/Views/Home/TrainerRegisteredUsers.cshtml
@{
    ViewBag.Title = "TrainerRegisteredUsers";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
    var userList = ViewBag.RegisteredUsers;
    var programId = ViewBag.ProgramId;
}
<style>
    body {
        margin: auto;
    }
</style>
<h2>Registered Users Of My Program</h2>

<div class="container">
    <div class="row text-center user-list" style="margin-top: 50px;">

        <div class="list-group">
            @foreach (var user in userList)
            {
                <a class="list-group-item " style="width: 600px; float: left; margin-top: 10px; margin-left: 35px;">
                    <h4 class="list-group-item-heading">@user.Username</h4>
                    <p class="list-group-item-text">@user.Email</p>
                </a>
                <a href="@Url.Action("TrainerWeightLogOfUser", "Home", new {programId = programId, userId = @user.ID})" class="list-group-item active" style="width: 250px; float: left; margin-left: 50px; margin-top: 17px;">
                    <p class="list-group-item-heading"> See Weight Logs <i class="fa fa-arrow-right" aria-hidden="true"></i></p>
                </a>
                <br />
            }
        </div>
    </div>
</div>