Workout.Web/Controllers/AdminController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Workout.Business.Models.Enums;
using Workout.Business.Models.RequestModels;
using Workout.Business.Processes;
using Workout.Data;
using Workout.Data.Processes;

namespace Workout.Web.Controllers
{
    public class AdminController : Controller
    {
        #region Decleration
        private WorkoutProcesses workoutProcesses = new WorkoutProcesses();
        private UserProcesses userProcesses = new UserProcesses();
        #endregion


        #region Error Handling
        protected override void OnException(ExceptionContext filterContext)
        {
            Exception ex = filterContext.Exception;
            LogProcesses.ErrorLog(ex);
        }
        #endregion

        [HttpPost]
        public ActionResult DoLogin(string username, string password, string url)
        {
            var sessionHelper = new SessionProcesses();
            var response = sessionHelper.GetAdminLoginResponse(username, password);

            if (response.ResponseCode == 1 || response.ResponseCode == 2)
            {
                if (string.IsNullOrEmpty(url))
                    return RedirectToAction("RegisterRequests");
                else
                    return RedirectToAction(url);
            }
            else
                return RedirectToAction("Login", new { url = "Login", validation = false });

        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            if (HttpContext.Request.Cookies["SIDA"] != null)
            {
                var sessionHelper = new SessionProcesses();
                sessionHelper.GetAdminLogoutResponse(HttpContext.Request.Cookies["SIDA"].Value);
                return RedirectToAction("RegisterRequests");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        [HttpGet]
        public ActionResult ErrorPage()
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());
                return View();
            }
            else
                return RedirectToAction("Login", new { url = "ErrorPage" });
        }

        [HttpGet]
        public ActionResult TrainerCertificates(string username = null)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {
                var certificates = new List<Certificates>();
                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());
                var users = userProcesses.GetDeactiveProfiles();
                ViewBag.UserList = users.UserList;
                if (!string.IsNullOrEmpty(username))
                {
                    var userId = userProcesses.GetUserIdByUsername(username);
                    certificates = userProcesses.GetCertificatesForUser(userId);
                }
                else
                {
                    certificates = userProcesses.GetCertificatesForAllUsers();
                }
                ViewBag.Certificates = certificates;
                return View();
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        [HttpGet]
        public ActionResult TrainerDeactivate(string username = null)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());
                List<Users> users = new List<Users>();

                if (!string.IsNullOrEmpty(username))
                {
                    users.Add(userProcesses.GetTrainerByUsername(username).FirstOrDefault());
                }

                ViewBag.UserList = users;
                return View();
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        public ActionResult BanTrainer(Guid userId)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());

                if (userId != Guid.Empty)
                {
                    if (userProcesses.BanTrainer(userId))
                        return RedirectToAction("TrainerDeactivate");

                }
                return RedirectToAction("TrainerDeactivate");
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        [HttpGet]
        public ActionResult ProgramDeactivate(string programTitle = null)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());
                List<Programs> programs = new List<Programs>();

                if (!string.IsNullOrEmpty(programTitle))
                {
                    programs = workoutProcesses.GetProgramsWithTitle(programTitle, 0);
                }

                ViewBag.ProgramList = programs;
                return View();
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        public ActionResult BanProgram(Guid programId)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());

                if (programId != Guid.Empty)
                {
                    if (userProcesses.BanProgram(programId))
                        return RedirectToAction("ProgramDeactivate");

                }
                return RedirectToAction("ProgramDeactivate");
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        public ActionResult ActivateBannedProgram(Guid programId)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());

                if (programId != Guid.Empty)
                {
                    if (userProcesses.ActivateBannedProgram(programId))
                        return RedirectToAction("ProgramDeactivate");

                }
                return RedirectToAction("ProgramDeactivate");
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        [HttpGet]
        public ActionResult UserDeactivate(string username = null)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {

                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());
                List<Users> users = new List<Users>();

                if (!string.IsNullOrEmpty(username))
                {
                    users.Add(userProcesses.GetUserByUsername(username));
                }

                ViewBag.UserList = users;
                return View();
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        public ActionResult BanUser(Guid userId)
        {
            var sessionHelper = new SessionProcesses();
            var currentUser = sessionHelper.GetCurrentUser(UserRole.Admin);
            if (currentUser != null)
            {
                ViewBag.User = currentUser;
                ViewBagSet(currentUser.Username.ToUpper(), currentUser.ID.ToString());

                if (userId != Guid.Empty)
                {
                    if (userProcesses.BanUser(userId))
                        return RedirectToAction("UserDeactivate");

                }
                return RedirectToAction("UserDeactivate");
            }
            else
                return RedirectToAction("Login", new { url = "RegisterRequests" });
        }

        [HttpGet]
        private void ViewBagSet(string username, string userId)
        {
            ViewBag.Username = username.ToUpper();
            ViewBag.UserId = userId;
        }
        [HttpPost]
        public JsonResult DeleteComment()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<DeleteCommentRequest>(ReadJson());
                return Json(workoutProcesses.DeleteComment(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }

Workout.Web/Controllers/BusinessController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.IO;
using Workout.Business.Models.RequestModels;
using Workout.Business.Processes;
using Workout.Data.Processes;

namespace Workout.Web.Controllers
{
    public class BusinessController : Controller
    {
        #region Decleration
        private UserProcesses userProcesses = new UserProcesses();
        private string jsonString = String.Empty;

        #endregion

        #region Error Handling
        protected override void OnException(ExceptionContext filterContext)
        {
            Exception ex = filterContext.Exception;
            LogProcesses.ErrorLog(ex);
        }
        #endregion

        #region Registration
        [HttpPost]
        public JsonResult UserRegister()
        {
            try
            {
                var user = JsonConvert.DeserializeObject<UserRequests>(ReadJson());
                return Json(userProcesses.Register(user), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region User Update
        [HttpPost]
        public JsonResult UserUpdate()
        {
            try
            {
                var user = JsonConvert.DeserializeObject<UserUpdateRequests>(ReadJson());
                return Json(userProcesses.UpdateUser(user), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Login

        public JsonResult UserLogin()
        {
            try
            {
                var loginReq = JsonConvert.DeserializeObject<LoginRequest>(ReadJson());
                return Json(userProcesses.Login(loginReq), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult CheckLogin()
        {
            try
            {
                return Json(userProcesses.CheckLogin(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult Logout()
        {
            try
            {
                var result = userProcesses.Logout();
                if (result.Response.ResponseCode == 1)
                    return RedirectToAction("Login", "Home");
                else
                    return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult CheckSecurityAnswer()
        {
            try
            {
                var securityReq = JsonConvert.DeserializeObject<SecurityAnswerRequest>(ReadJson());
                return Json(userProcesses.CheckSequrityAnswer(securityReq), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult GetUserWeight()
        {
            try
            {
                var getWeightReq = JsonConvert.DeserializeObject<GetWeightForUserRequest>(ReadJson());
                return Json(userProcesses.GetWeightForUser(getWeightReq));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public JsonResult GetUserWeightForProgram()
        {
            try
            {
                var getWeightReq = JsonConvert.DeserializeObject<GetWeightForProgramRequest>(ReadJson());
                return Json(userProcesses.GetWeightForProgram(getWeightReq));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public JsonResult SetUserWeight()
        {
            try
            {
                var setWeightReq = JsonConvert.DeserializeObject<SetWeightForUserRequest>(ReadJson());
                return Json(userProcesses.SetWeightForUser(setWeightReq));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region Profile Functions
        public JsonResult GetProfileInformation()
        {
            try
            {
                return Json(userProcesses.GetProfile(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult UpdateProfile()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<UpdateProfileRequest>(ReadJson());
                return Json(userProcesses.UpdateProfile(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult HeightWeightUpdate()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<HeightWeightUpdateRequest>(ReadJson());
                return Json(userProcesses.UpdateHeightWeight(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult TrainerView()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<TrainerViewRequest>(ReadJson());
                return Json(userProcesses.TrainerViewUpdate(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult AddCertificate()
        {
            try
            {
                var request = JsonConvert.DeserializeObject<AddCertificateRequest>(ReadJson());
                return Json(userProcesses.AddCertification(request), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region Common Functions
        private string ReadJson()
        {
            try
            {
                JsonConvert.DefaultSettings = () => new JsonSerializerSettings() { DateFormatString = "dd-MM-yyyy" };
                Request.InputStream.Position = 0;

                using (var inputStream = new StreamReader(Request.InputStream))
                {
                    return inputStream.ReadToEnd();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
    }
}

Workout.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Say Your Idea Management Panel">
    <meta name="author" content="Gokhan Yilmaz Gokun">


    <title>Workout - @ViewBag.Title - Back Office</title>

    <link href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Assets/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="~/Assets/dist/css/timeline.css" rel="stylesheet">
    <link href="~/Assets/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/Assets/bower_components/morrisjs/morris.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Assets/chat.css" rel="stylesheet" />
    <link href="~/Assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
    <link href="~/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Assets/style.css" rel="stylesheet" />
    <link href="~/Assets/form-elements.css" rel="stylesheet" />
    <link href="~/Assets/css/jquery-ui.min.css" rel="stylesheet" />

    <script src="~/Assets/js/jquery-1.11.1.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/Home.js"></script>
    <script src="~/Assets/js/jquery.validate.min.js"></script>
    <script src="~/Assets/js/Functions.js"></script>
    <script src="~/Assets/js/moment.min.js"></script>
    <link href="~/Assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Assets/js/jquery-ui.min.js"></script>


    <script src="~/Assets/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="~/Assets/js/validator.min.js"></script>
    <script src="~/Assets/bower_components/raphael/raphael-min.js"></script>
    <script src="~/Assets/bower_components/morrisjs/morris.min.js"></script>
    <script src="~/Assets/dist/js/sb-admin-2.js"></script>

    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
    @if (false)
    {
        <script src="../../Assets/js/jquery-1.7.2-vsdoc.js" type="text/javascript"></script>
    }

    <script>
        $(document).ready(function () {
            if ($('.table').has("tr").length > 0) {

                $('th').click(function () {
                    var table = $(this).parents('table').eq(0);
                    var rows = table.find("tr:not(:has('th'))").toArray().sort(comparer($(this).index()));
                    this.asc = !this.asc;
                    if (!this.asc) { rows = rows.reverse() }
                    for (var i = 0; i < rows.length; i++) { table.append(rows[i]) }
                });

                function comparer(index) {
                    return function (a, b) {
                        var valA = getCellValue(a, index), valB = getCellValue(b, index);
                        return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.localeCompare(valB);
                    };
                }
                function getCellValue(row, index) { return $(row).children('td').eq(index).html() }

                $('table').each(function () {
                    var table = $(this);
                    var headers = table.find('th').length;
                    var filterrow = $('<tr>').insertAfter($(this).find('th:last()').parent());
                    for (var i = 0; i < headers; i++) {
                        if (i < headers - 1) {
                            filterrow.append($('<th>').append($('<input>').attr('type', 'text').attr("placeholder", "Filter text").keyup(function () {
                                table.find('tr').show();
                                filterrow.find('input[type=text]').each(function () {
                                    var index = $(this).parent().index() + 1;
                                    var filter = $(this).val() != '';
                                    $(this).toggleClass('filtered', filter);
                                    if (filter) {
                                        var el = 'td:nth-child(' + index + ')';
                                        var criteria = ":contains('" + $(this).val() + "')";
                                        table.find(el + ':not(' + criteria + ')').parent().hide();
                                    }
                                });
                            })));
                        } else {
                            filterrow.append($('<th>').append($('<span>')));
                        }
                    }
                    filterrow.append($('<th>').append($('<input>').attr('type', 'button').val('Clear Filter').click(function () {
                        $(this).parent().parent().find('input[type=text]').val('').toLowerCase().toggleClass('filtered', false);
                        table.find('tr').show();
                    })));
                });
            }
        });
    </script>
    <style>
        input {
            width: 150px;
        }
    </style>

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("RegisterRequests","Admin")">Welcome, @ViewBag.Username</a>
            </div>
            <ul class="nav navbar-top-links navbar-right" style="margin-right: 15px; margin-top: 5px;">
                <a href="@Url.Action("Logout", "Admin")"><i class="fa fa-sign-out fa-fw"></i>Logout</a>

            </ul>


            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav in" id="side-menu">
                        <li>
                            <a href="@Url.Action("Trainers", "Admin")" class="active"><i class="fa fa-spinner" aria-hidden="true"></i> Trainers </a>
                            <a href="@Url.Action("RegisterRequests", "Admin")" class="active"><i class="fa fa-spinner" aria-hidden="true"></i> Activate Users </a>
                            <a href="@Url.Action("TrainerCertificates", "Admin")" class="active"><i class="fa fa-id-card " aria-hidden="true"></i> Trainer Certificates </a>
                            <a href="@Url.Action("TrainerDeactivate", "Admin")" class="active"><i class="fa fa-user-o " aria-hidden="true"></i> Trainer Deactivate </a>
                            <a href="@Url.Action("ProgramDeactivate", "Admin")" class="active"><i class="fa fa-user-o " aria-hidden="true"></i> Program Deactivate/Activate </a>
                            <a href="@Url.Action("UserDeactivate", "Admin")" class="active"><i class="fa fa-user-o " aria-hidden="true"></i> User Deactivate </a>
                        </li>

                    </ul>
                </div>

            </div>

        </nav>
        <div id="page-wrapper" style="min-height: 914px;">
            @RenderBody()
        </div>


    </div>




</body>
</html>

Workout.Web/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Workouts - Be Fit! - @ViewBag.Title</title>

    <link href="~/Assets/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/css/home.css" rel="stylesheet"/>
    <link href="~/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Assets/style.css" rel="stylesheet" />
    <link href="~/Assets/form-elements.css" rel="stylesheet" />
    <link href="~/Assets/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src="~/Assets/js/jquery-1.11.1.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/Home.js"></script>
    <script src="~/Assets/js/jquery.validate.min.js"></script>
    <script src="~/Assets/js/Functions.js"></script>
    <script src="~/Assets/js/moment.min.js"></script>
    <link href="~/Assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Assets/js/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($('.table').has("tr").length > 0) {

                $('th').click(function () {
                    var table = $(this).parents('table').eq(0);
                    var rows = table.find("tr:not(:has('th'))").toArray().sort(comparer($(this).index()));
                    this.asc = !this.asc;
                    if (!this.asc) { rows = rows.reverse() }
                    for (var i = 0; i < rows.length; i++) { table.append(rows[i]) }
                });

                function comparer(index) {
                    return function (a, b) {
                        var valA = getCellValue(a, index), valB = getCellValue(b, index);
                        return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.localeCompare(valB);
                    };
                }
                function getCellValue(row, index) { return $(row).children('td').eq(index).html() }

                $('table').each(function () {
                    var table = $(this);
                    var headers = table.find('th').length;
                    var filterrow = $('<tr>').insertAfter($(this).find('th:last()').parent());
                    for (var i = 0; i < headers; i++) {
                        if (i < headers - 1) {
                            filterrow.append($('<th>').append($('<input>').attr('type', 'text').attr("placeholder", "Filter text").keyup(function () {
                                table.find('tr').show();
                                filterrow.find('input[type=text]').each(function () {
                                    var index = $(this).parent().index() + 1;
                                    var filter = $(this).val() != '';
                                    $(this).toggleClass('filtered', filter);
                                    if (filter) {
                                        var el = 'td:nth-child(' + index + ')';
                                        var criteria = ":contains('" + $(this).val() + "')";
                                        table.find(el + ':not(' + criteria + ')').parent().hide();
                                    }
                                });
                            })));
                        } else {
                            filterrow.append($('<th>').append($('<span>')));
                        }
                    }
                    filterrow.append($('<th>').append($('<input>').attr('type', 'button').val('Clear Filter').click(function () {
                        $(this).parent().parent().find('input[type=text]').val('').toLowerCase().toggleClass('filtered', false);
                        table.find('tr').show();
                    })));
                });
            }
        });
    </script>
    <style>
        input {
            width: 150px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Workouts - Be Fit!</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                @{
                    if (ViewBag.Username != null)
                    {
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="@Url.Action("AllPrograms", "Home")">Programs</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Trainers", "Home")">Trainers</a>
                            </li>

                        </ul>
                    }
                }
                    <ul class="nav navbar-nav navbar-right">
                    @{
                        if (ViewBag.Username != null)
                        {
                            <span class="profile-name">Welcome, @ViewBag.Username</span>

                            <a href="@Url.Action("Profile", "Home")" class="btn btn-primary profile-btn"><i class="fa fa-user"></i> Profile</a>

                            <a href="@Url.Action("Logout", "Business")" class="btn btn-danger profile-btn"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Home")" class="btn btn-primary profile-btn"><i class="fa fa-sign-out fa-fw"></i> Login</a>
                        }
                    }

                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <div class="container">
        
    </div>
    <hr>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright Workouts &copy; 2017</p>
            </div>
        </div>
    </footer>
</body>
</html>